In [1]:
%run C:\Users\Joshua\Jupyter_Notebook_Folders\MacroData\Add_Data_DB.ipynb

In [2]:
seriesID = "CUUR0000SA0"
json_data = get_BLS_data(seriesID, 1979, 1998)
json_data

{'status': 'REQUEST_SUCCEEDED',
 'responseTime': 279,
 'message': [],
 'Results': {'series': [{'seriesID': 'CUUR0000SA0',
    'catalog': {'series_title': 'All items in U.S. city average, all urban consumers, not seasonally adjusted',
     'series_id': 'CUUR0000SA0',
     'seasonality': 'Not Seasonally Adjusted',
     'survey_name': 'CPI for All Urban Consumers (CPI-U)',
     'survey_abbreviation': 'CU',
     'measure_data_type': 'All items',
     'area': 'U.S. city average',
     'item': 'All items'},
    'data': [{'year': '1998',
      'period': 'M12',
      'periodName': 'December',
      'value': '163.9',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M11',
      'periodName': 'November',
      'value': '164.0',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M10',
      'periodName': 'October',
      'value': '164.0',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M09',
      'periodName': 'September',
      'value': '163.6',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M08',
      'periodName': 'August',
      'value': '163.4',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M07',
      'periodName': 'July',
      'value': '163.2',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M06',
      'periodName': 'June',
      'value': '163.0',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M05',
      'periodName': 'May',
      'value': '162.8',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M04',
      'periodName': 'April',
      'value': '162.5',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M03',
      'periodName': 'March',
      'value': '162.2',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M02',
      'periodName': 'February',
      'value': '161.9',
      'footnotes': [{}]},
     {'year': '1998',
      'period': 'M01',
      'periodName': 'January',
      'value': '161.6',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M12',
      'periodName': 'December',
      'value': '161.3',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M11',
      'periodName': 'November',
      'value': '161.5',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M10',
      'periodName': 'October',
      'value': '161.6',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M09',
      'periodName': 'September',
      'value': '161.2',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M08',
      'periodName': 'August',
      'value': '160.8',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M07',
      'periodName': 'July',
      'value': '160.5',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M06',
      'periodName': 'June',
      'value': '160.3',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M05',
      'periodName': 'May',
      'value': '160.1',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M04',
      'periodName': 'April',
      'value': '160.2',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M03',
      'periodName': 'March',
      'value': '160.0',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M02',
      'periodName': 'February',
      'value': '159.6',
      'footnotes': [{}]},
     {'year': '1997',
      'period': 'M01',
      'periodName': 'January',
      'value': '159.1',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M12',
      'periodName': 'December',
      'value': '158.6',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M11',
      'periodName': 'November',
      'value': '158.6',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M10',
      'periodName': 'October',
      'value': '158.3',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M09',
      'periodName': 'September',
      'value': '157.8',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M08',
      'periodName': 'August',
      'value': '157.3',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M07',
      'periodName': 'July',
      'value': '157.0',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M06',
      'periodName': 'June',
      'value': '156.7',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M05',
      'periodName': 'May',
      'value': '156.6',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M04',
      'periodName': 'April',
      'value': '156.3',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M03',
      'periodName': 'March',
      'value': '155.7',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M02',
      'periodName': 'February',
      'value': '154.9',
      'footnotes': [{}]},
     {'year': '1996',
      'period': 'M01',
      'periodName': 'January',
      'value': '154.4',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M12',
      'periodName': 'December',
      'value': '153.5',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M11',
      'periodName': 'November',
      'value': '153.6',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M10',
      'periodName': 'October',
      'value': '153.7',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M09',
      'periodName': 'September',
      'value': '153.2',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M08',
      'periodName': 'August',
      'value': '152.9',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M07',
      'periodName': 'July',
      'value': '152.5',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M06',
      'periodName': 'June',
      'value': '152.5',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M05',
      'periodName': 'May',
      'value': '152.2',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M04',
      'periodName': 'April',
      'value': '151.9',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M03',
      'periodName': 'March',
      'value': '151.4',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M02',
      'periodName': 'February',
      'value': '150.9',
      'footnotes': [{}]},
     {'year': '1995',
      'period': 'M01',
      'periodName': 'January',
      'value': '150.3',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M12',
      'periodName': 'December',
      'value': '149.7',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M11',
      'periodName': 'November',
      'value': '149.7',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M10',
      'periodName': 'October',
      'value': '149.5',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M09',
      'periodName': 'September',
      'value': '149.4',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M08',
      'periodName': 'August',
      'value': '149.0',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M07',
      'periodName': 'July',
      'value': '148.4',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M06',
      'periodName': 'June',
      'value': '148.0',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M05',
      'periodName': 'May',
      'value': '147.5',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M04',
      'periodName': 'April',
      'value': '147.4',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M03',
      'periodName': 'March',
      'value': '147.2',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M02',
      'periodName': 'February',
      'value': '146.7',
      'footnotes': [{}]},
     {'year': '1994',
      'period': 'M01',
      'periodName': 'January',
      'value': '146.2',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M12',
      'periodName': 'December',
      'value': '145.8',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M11',
      'periodName': 'November',
      'value': '145.8',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M10',
      'periodName': 'October',
      'value': '145.7',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M09',
      'periodName': 'September',
      'value': '145.1',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M08',
      'periodName': 'August',
      'value': '144.8',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M07',
      'periodName': 'July',
      'value': '144.4',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M06',
      'periodName': 'June',
      'value': '144.4',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M05',
      'periodName': 'May',
      'value': '144.2',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M04',
      'periodName': 'April',
      'value': '144.0',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M03',
      'periodName': 'March',
      'value': '143.6',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M02',
      'periodName': 'February',
      'value': '143.1',
      'footnotes': [{}]},
     {'year': '1993',
      'period': 'M01',
      'periodName': 'January',
      'value': '142.6',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M12',
      'periodName': 'December',
      'value': '141.9',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M11',
      'periodName': 'November',
      'value': '142.0',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M10',
      'periodName': 'October',
      'value': '141.8',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M09',
      'periodName': 'September',
      'value': '141.3',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M08',
      'periodName': 'August',
      'value': '140.9',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M07',
      'periodName': 'July',
      'value': '140.5',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M06',
      'periodName': 'June',
      'value': '140.2',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M05',
      'periodName': 'May',
      'value': '139.7',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M04',
      'periodName': 'April',
      'value': '139.5',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M03',
      'periodName': 'March',
      'value': '139.3',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M02',
      'periodName': 'February',
      'value': '138.6',
      'footnotes': [{}]},
     {'year': '1992',
      'period': 'M01',
      'periodName': 'January',
      'value': '138.1',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M12',
      'periodName': 'December',
      'value': '137.9',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M11',
      'periodName': 'November',
      'value': '137.8',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M10',
      'periodName': 'October',
      'value': '137.4',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M09',
      'periodName': 'September',
      'value': '137.2',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M08',
      'periodName': 'August',
      'value': '136.6',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M07',
      'periodName': 'July',
      'value': '136.2',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M06',
      'periodName': 'June',
      'value': '136.0',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M05',
      'periodName': 'May',
      'value': '135.6',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M04',
      'periodName': 'April',
      'value': '135.2',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M03',
      'periodName': 'March',
      'value': '135.0',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M02',
      'periodName': 'February',
      'value': '134.8',
      'footnotes': [{}]},
     {'year': '1991',
      'period': 'M01',
      'periodName': 'January',
      'value': '134.6',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M12',
      'periodName': 'December',
      'value': '133.8',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M11',
      'periodName': 'November',
      'value': '133.8',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M10',
      'periodName': 'October',
      'value': '133.5',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M09',
      'periodName': 'September',
      'value': '132.7',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M08',
      'periodName': 'August',
      'value': '131.6',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M07',
      'periodName': 'July',
      'value': '130.4',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M06',
      'periodName': 'June',
      'value': '129.9',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M05',
      'periodName': 'May',
      'value': '129.2',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M04',
      'periodName': 'April',
      'value': '128.9',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M03',
      'periodName': 'March',
      'value': '128.7',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M02',
      'periodName': 'February',
      'value': '128.0',
      'footnotes': [{}]},
     {'year': '1990',
      'period': 'M01',
      'periodName': 'January',
      'value': '127.4',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M12',
      'periodName': 'December',
      'value': '126.1',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M11',
      'periodName': 'November',
      'value': '125.9',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M10',
      'periodName': 'October',
      'value': '125.6',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M09',
      'periodName': 'September',
      'value': '125.0',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M08',
      'periodName': 'August',
      'value': '124.6',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M07',
      'periodName': 'July',
      'value': '124.4',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M06',
      'periodName': 'June',
      'value': '124.1',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M05',
      'periodName': 'May',
      'value': '123.8',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M04',
      'periodName': 'April',
      'value': '123.1',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M03',
      'periodName': 'March',
      'value': '122.3',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M02',
      'periodName': 'February',
      'value': '121.6',
      'footnotes': [{}]},
     {'year': '1989',
      'period': 'M01',
      'periodName': 'January',
      'value': '121.1',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M12',
      'periodName': 'December',
      'value': '120.5',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M11',
      'periodName': 'November',
      'value': '120.3',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M10',
      'periodName': 'October',
      'value': '120.2',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M09',
      'periodName': 'September',
      'value': '119.8',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M08',
      'periodName': 'August',
      'value': '119.0',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M07',
      'periodName': 'July',
      'value': '118.5',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M06',
      'periodName': 'June',
      'value': '118.0',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M05',
      'periodName': 'May',
      'value': '117.5',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M04',
      'periodName': 'April',
      'value': '117.1',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M03',
      'periodName': 'March',
      'value': '116.5',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M02',
      'periodName': 'February',
      'value': '116.0',
      'footnotes': [{}]},
     {'year': '1988',
      'period': 'M01',
      'periodName': 'January',
      'value': '115.7',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M12',
      'periodName': 'December',
      'value': '115.4',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M11',
      'periodName': 'November',
      'value': '115.4',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M10',
      'periodName': 'October',
      'value': '115.3',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M09',
      'periodName': 'September',
      'value': '115.0',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M08',
      'periodName': 'August',
      'value': '114.4',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M07',
      'periodName': 'July',
      'value': '113.8',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M06',
      'periodName': 'June',
      'value': '113.5',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M05',
      'periodName': 'May',
      'value': '113.1',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M04',
      'periodName': 'April',
      'value': '112.7',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M03',
      'periodName': 'March',
      'value': '112.1',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M02',
      'periodName': 'February',
      'value': '111.6',
      'footnotes': [{}]},
     {'year': '1987',
      'period': 'M01',
      'periodName': 'January',
      'value': '111.2',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M12',
      'periodName': 'December',
      'value': '110.5',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M11',
      'periodName': 'November',
      'value': '110.4',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M10',
      'periodName': 'October',
      'value': '110.3',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M09',
      'periodName': 'September',
      'value': '110.2',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M08',
      'periodName': 'August',
      'value': '109.7',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M07',
      'periodName': 'July',
      'value': '109.5',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M06',
      'periodName': 'June',
      'value': '109.5',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M05',
      'periodName': 'May',
      'value': '108.9',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M04',
      'periodName': 'April',
      'value': '108.6',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M03',
      'periodName': 'March',
      'value': '108.8',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M02',
      'periodName': 'February',
      'value': '109.3',
      'footnotes': [{}]},
     {'year': '1986',
      'period': 'M01',
      'periodName': 'January',

In [3]:
df = create_df_from_json_for_sqlite(seriesID, "MacroData.sqlite3")

In [4]:
create_table(df, seriesID, 'MacroData.sqlite3')

Table  CUUR0000SA0  already exists

In [5]:
df_AddDB, df_dup_data, df_inconsistent_data = check_duplicate_data(df, seriesID, 'MacroData.sqlite3')

# Deal with duplicate data
if not df_dup_data.empty:
    print("Duplicate Data: \n", df_dup_data)
else:
    del df_dup_data
    
# Deal with inconsistent data
if not df_inconsistent_data.empty:
    print("DATA FROM DATAFRAME DOES INCONSISTENT WITH DATA IN DATABASE: \n", df_inconsistent_data)
else:
    del df_inconsistent_data

df_AddDB

,year,period,periodName,value,date,description
720,1979,M01,January,68.3,1979-01,"CPI for All Urban Consumers (CPI-U), All items..."
721,1979,M02,February,69.1,1979-02,"CPI for All Urban Consumers (CPI-U), All items..."
722,1979,M03,March,69.8,1979-03,"CPI for All Urban Consumers (CPI-U), All items..."
723,1979,M04,April,70.6,1979-04,"CPI for All Urban Consumers (CPI-U), All items..."
724,1979,M05,May,71.5,1979-05,"CPI for All Urban Consumers (CPI-U), All items..."
...,...,...,...,...,...,...
955,1998,M08,August,163.4,1998-08,"CPI for All Urban Consumers (CPI-U), All items..."
956,1998,M09,September,163.6,1998-09,"CPI for All Urban Consumers (CPI-U), All items..."
957,1998,M10,October,164.0,1998-10,"CPI for All Urban Consumers (CPI-U), All items..."
958,1998,M11,November,164.0,1998-11,"CPI for All Urban Consumers (CPI-U), All items..."
959,1998,M12,December,163.9,1998-12,"CPI for All Urban Consumers (CPI-U), All items..."

In [6]:
add_to_database(df_AddDB, seriesID, 'MacroData.sqlite3')

Data added to DB:
      year period periodName  value     date  \
720  1979    M01    January   68.3  1979-01
721  1979    M02   February   69.1  1979-02
722  1979    M03      March   69.8  1979-03
723  1979    M04      April   70.6  1979-04
724  1979    M05        May   71.5  1979-05
..    ...    ...        ...    ...      ...
955  1998    M08     August  163.4  1998-08
956  1998    M09  September  163.6  1998-09
957  1998    M10    October  164.0  1998-10
958  1998    M11   November  164.0  1998-11
959  1998    M12   December  163.9  1998-12

                                           description
720  CPI for All Urban Consumers (CPI-U), All items...
721  CPI for All Urban Consumers (CPI-U), All items...
722  CPI for All Urban Consumers (CPI-U), All items...
723  CPI for All Urban Consumers (CPI-U), All items...
724  CPI for All Urban Consumers (CPI-U), All items...
..                                                 ...
955  CPI for All Urban Consumers (CPI-U), All items...
956  CPI for All Urban Consumers (CPI-U), All items...
957  CPI for All Urban Consumers (CPI-U), All items...
958  CPI for All Urban Consumers (CPI-U), All items...
959  CPI for All Urban Consumers (CPI-U), All items...

[240 rows x 6 columns]

In [7]:
df_cpi_not_seasonal = table_to_df(seriesID, 'MacroData.sqlite3')
df_cpi_not_seasonal

,index,year,period,periodName,value,date,description
0,0,1919,M01,January,16.5,1919-01,"CPI for All Urban Consumers (CPI-U), All items..."
1,1,1919,M02,February,16.2,1919-02,"CPI for All Urban Consumers (CPI-U), All items..."
2,2,1919,M03,March,16.4,1919-03,"CPI for All Urban Consumers (CPI-U), All items..."
3,3,1919,M04,April,16.7,1919-04,"CPI for All Urban Consumers (CPI-U), All items..."
4,4,1919,M05,May,16.9,1919-05,"CPI for All Urban Consumers (CPI-U), All items..."
...,...,...,...,...,...,...,...
955,955,1998,M08,August,163.4,1998-08,"CPI for All Urban Consumers (CPI-U), All items..."
956,956,1998,M09,September,163.6,1998-09,"CPI for All Urban Consumers (CPI-U), All items..."
957,957,1998,M10,October,164.0,1998-10,"CPI for All Urban Consumers (CPI-U), All items..."
958,958,1998,M11,November,164.0,1998-11,"CPI for All Urban Consumers (CPI-U), All items..."
959,959,1998,M12,December,163.9,1998-12,"CPI for All Urban Consumers (CPI-U), All items..."

In [ ]:
#con = db.connect('MacroData.sqlite3')
#c = con.cursor()
#c.execute("DROP TABLE " + seriesID)
#con.commit()
#con.close()